
### GET ALL ROWS

GET http://localhost:8080/posts

### GET ROW BY ID

GET http://localhost:8080/posts/1

### DELETE ROW BY ID

DELETE http://localhost:8080/posts/3

### ADD NEW ROW

POST http://localhost:8080/posts
Content-Type: application/json

{
    "content": "Announcement"
}